[WIP] Version 1.7.0
ndsev/zswag pull request #121
Opened 2024-06-24 16:23 UTC by josephbirkner

2024-07-09 12:34 UTC, josephbirkner commented on libs/zswagcl/src/openapi-parser.cpp
> +            if (requiredNode.as<bool>())
Must be
```suggestion
            if (!requiredNode.as<bool>())
```

2024-07-09 14:32 UTC, fklebert requested changes
In addition to the build stuff, I am missing tests especially for the OAClient extension with the server index.

2024-07-09 14:32 UTC, fklebert commented on CMakeLists.txt
> +  find_package(ZLIB CONFIG REQUIRED)
Please use a `if(NOT TARGET ZLIB)` guard here, so that the build also works in case a consumer project doesn't want to use conan and provides its own way of making zlib available via cmake.

2024-07-09 14:32 UTC, fklebert commented on CMakeLists.txt
> +  set(HTTPLIB_REQUIRE_ZLIB ON CACHE BOOL "Do not use zlib when compiling httplib." FORCE)
I do not get the message? "Do **not** use zlib"?
In addition: This does effectivly the same as the `find_package` call above (see https://github.com/yhirose/cpp-httplib/blob/c8bcaf8a913f1ac087b076488e0cbbc272cccd19/CMakeLists.txt#L135)
Maybe it is better to guard the zlib and then use `set(HTTPLIB_IS_USING_ZLIB TRUE)` as indicated in the link above?

2024-07-09 16:03 UTC, josephbirkner commented on CMakeLists.txt
> +  set(HTTPLIB_REQUIRE_ZLIB ON CACHE BOOL "Do not use zlib when compiling httplib." FORCE)
Sorry, good catch. The message is wrong.

2024-07-17 07:47 UTC, fklebert commented on libs/httpcl/src/http-settings.cpp
> +        const_cast<Settings*>(this)->load();
A small remark:
We may want to put this into a try-catch so that we can re-aquire the mutex in the catch block in case load() throws... ?

2024-07-17 07:47 UTC, fklebert approved these changes
👍

2024-07-17 18:08 UTC, merged